apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git@github.com:wizardcommerce/kustomize-projects.git/projects/dialog-agent-service/env/dev?ref=c76c9621482d16dd778894c13b41b4b85c40ed87
